# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dd1fae7adeb741d73ef39f6403b17e2cf44843c2f965f08989fefa77d07e8a01b433b8870ecab0c800ba1fab680d3462d4b1e32dbf9fb76fcc708d6f3006416

test:
  secret_key_base: b7f6e264338884dbbb40cf4381f8f8c17c309d69e97d23ba052f74ccd8c26fa1024b1b3acbda327405542676e622789cb97c29d7643604e4283540bf0b4ece1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
